export const SOURCES = [
  { type: "processor", url: "https://www.viraindo.com/proc.html", icon: "💻" },
  {
    type: "motherboard",
    url: "https://www.viraindo.com/motherboard.html",
    icon: "🖥️",
  },
  { type: "storage", url: "https://www.viraindo.com/storage.html", icon: "💾" },
  { type: "RAM", url: "https://www.viraindo.com/memory.html", icon: "💾" },
  { type: "GPU", url: "https://www.viraindo.com/vga.html", icon: "🖥️" },
  { type: "psu", url: "https://www.viraindo.com/psu.html", icon: "💪" },
  { type: "display", url: "https://www.viraindo.com/lcd.html", icon: "🖥️" },
  { type: "case", url: "https://www.viraindo.com/casing.html", icon: "📦" },
  {
    type: "pc-branded",
    url: "https://www.viraindo.com/pcbranded.html",
    icon: "🖥️",
  },
  { type: "gadget", url: "https://www.viraindo.com/gadget.html", icon: "📱" },
  {
    type: "notebook",
    url: "https://www.viraindo.com/notebook.html",
    icon: "💻",
  },
];

export const COMPONENT_BRANDS = {
  processor: ["INTEL", "AMD"],
  motherboard: ["ASUS", "MSI", "GIGABYTE", "ASROCK", "BIOSTAR"],
  GPU: [
    "ASUS",
    "MSI",
    "GIGABYTE",
    "ZOTAC",
    "INNO3D",
    "GALAX",
    "POWERCOLOR",
    "SAPPHIRE",
    "XFX",
    "DIGITAL ALLIANCE",
  ],
  storage: [
    "SAMSUNG",
    "WESTERN DIGITAL",
    "WD",
    "SEAGATE",
    "KINGSTON",
    "CRUCIAL",
    "ADATA",
    "SANDISK",
    "TEAM",
  ],
  RAM: [
    "CORSAIR",
    "G.SKILL",
    "TEAMGROUP",
    "KINGSTON",
    "HYPERX",
    "ADATA",
    "V-COLOR",
    "GEIL",
  ],
  psu: [
    "CORSAIR",
    "COOLER MASTER",
    "SEASONIC",
    "FSP",
    "THERMALTAKE",
    "BE QUIET!",
    "DEEPCOOL",
    "AEROCOOL",
  ],
  display: [
    "LG",
    "SAMSUNG",
    "ASUS",
    "MSI",
    "GIGABYTE",
    "VIEWSONIC",
    "BENQ",
    "AOC",
    "ACER",
    "PHILIPS",
  ],
  case: [
    "CORSAIR",
    "COOLER MASTER",
    "LIAN LI",
    "NZXT",
    "HYTE",
    "DEEPCOOL",
    "THERMALTAKE",
    "ANTEC",
    "PRIME",
    "CUBE",
  ],
};
