export const SOURCES = [
  { type: "processor", url: "https://www.viraindo.com/proc.html", icon: "🧠" },
  {
    type: "motherboard",
    url: "https://www.viraindo.com/motherboard.html",
    icon: "🎛️",
  },
  { type: "storage", url: "https://www.viraindo.com/storage.html", icon: "💾" },
  { type: "ram", url: "https://www.viraindo.com/memory.html", icon: "📼" },
  { type: "gpu", url: "https://www.viraindo.com/vga.html", icon: "🎮" },
  { type: "psu", url: "https://www.viraindo.com/psu.html", icon: "🔌" },
  { type: "display", url: "https://www.viraindo.com/lcd.html", icon: "📺" },
  { type: "case", url: "https://www.viraindo.com/casing.html", icon: "📦" },
  {
    type: "pc-branded",
    url: "https://www.viraindo.com/pcbranded.html",
    icon: "🖥️",
  },
  { type: "gadget", url: "https://www.viraindo.com/gadget.html", icon: "📱" },
  {
    type: "notebook",
    url: "https://www.viraindo.com/notebook.html",
    icon: "💻",
  },
  {
    type: "cooler",
    url: "https://viraindo.com/cooler.html",
    icon: "💨",
  },
];

// NOTE: All keys are now lower‑case so they match SOURCES[].type exactly
export const COMPONENT_BRANDS = {
  processor: ["INTEL", "AMD"],
  motherboard: [
    "ASUS",
    "MSI",
    "GIGABYTE",
    "ASROCK",
    "BIOSTAR",
    "VARRO",
    "VENOMRX",
    "DIGITAL ALLIANCE",
    "BULLDOZER",
    "BULDOZER",
    "NZXT",
    "MAXSUN",
    "ARKTEK",
    "SAPPHIRE",
  ],
  gpu: [
    "ASUS",
    "MSI",
    "GIGABYTE",
    "ZOTAC",
    "INNO3D",
    "GALAX",
    "POWERCOLOR",
    "GAINWARD",
    "ASROCK",
    "SAPPHIRE",
    "XFX",
    "DIGITAL ALLIANCE",
    "IGAME",
    "LEADTEK",
    "MANLI",
    "MAXSUN",
    "PALIT",
    "PNY",
    "SPARKLE",
    "VENOMRX",
    "AMPTRON",
    "ARKTEK",
    "BIOSTAR",
    "COLORFUL",
    "DELL",
  ],
  storage: [
    "SAMSUNG",
    "WESTERN DIGITAL",
    "WD",
    "SEAGATE",
    "KINGSTON",
    "CRUCIAL",
    "ADATA",
    "SANDISK",
    "TEAM",
    "TOSHIBA",
    "TERRAMASTER",
    "QNAP",
    "SYNOLOGY",
    "ASUSTOR",
    "LEXAR",
    "HITACHI",
    "DELL",
    "ACER",
    "APACER",
    "BIWIN",
    "APPLE",
    "MSI",
    "GIGABYTE",
    "CORSAIR",
    "INTEL",
    "CUBE GAMING",
    "CADDY",
    "FRACTAL",
    "ORICO",
    "KLEVV",
    "LACIE",
    "MICRON",
    "PARADOX",
    "PATRIOT",
    "PNY",
    "SK HYNIX",
    "SOLIDIGM",
    "TRANSCEND",
    "V-GEN",
    "VENOMRX",
    "THECUS",
    "PHANTEKS",
    "LINKSYS",
    "ZHITAI",
  ],
  ram: [
    "CORSAIR",
    "G.SKILL",
    "TEAMGROUP",
    "KINGSTON",
    "HYPERX",
    "ADATA",
    "V-COLOR",
    "GEIL",
    "V-GEN",
    "VENOMRX",
    "SAMSUNG",
    "GIGABYTE",
    "RAMAXEL",
    "CUBE GAMING",
    "GALAX",
    "PATRIOT",
    "TEAM",
    "KLEVV",
    "LEXAR",
    "PNY",
    "ACER",
    "TRANSCEND",
    "CRUCIAL",
  ],
  psu: [
    "1STPLAYER",
    "ASROCK",
    "ADATA",
    "AEROCOOL",
    "AIGO",
    "ANTEC",
    "ARMAGGEDDON",
    "ACE",
    "ASUS",
    "BIOSTAR",
    "BASIC",
    "COUGAR",
    "CUBE GAMING",
    "CORSAIR",
    "COOLER MASTER",
    "OCYPUS",
    "SEASONIC",
    "FSP",
    "THERMALTAKE",
    "BE QUIET!",
    "DEEPCOOL",
    "DAZUMBA",
    "DIGITAL ALLIANCE",
    "ENERMAX",
    "ENLIGHT",
    "FRACTAL",
    "MONTECH",
    "MSI",
    "SUPER FLOWER",
    "GAMDIAS",
    "GAMEMAX",
    "GIGABYTE",
    "GALAX",
    "INNOVATION",
    "LIAN LI",
    "NZXT",
    "PARADOX",
    "PCCOOLER",
    "PHANTEKS",
    "POWERLOGIC",
    "POWER UP",
    "PRIME",
    "REDWOLF",
    "SEGOTEP",
    "SILVERSTONE",
    "SIMBADDA",
    "THERMALTAKE",
    "ZALMAN",
    "VENOMRX",
  ],
  display: [
    "ACER",
    "AOC",
    "APPLE",
    "ARMAGGEDDON",
    "ASROCK",
    "ASUS",
    "BENQ",
    "COOLER MASTER",
    "CUBE GAMING",
    "DAHUA",
    "DELL",
    "GIGABYTE",
    "HP",
    "LENOVO",
    "LG",
    "MSI",
    "PHILIPS",
    "QWERTY",
    "SAMSUNG",
    "SPC",
    "TCL",
    "UNIARCH",
    "VIEWSONIC",
    "XIAOMI",
  ],
  case: [
    "ABKONCORE",
    "ACE POWER",
    "ADATA",
    "AEROCOOL",
    "AIGO",
    "ALCATROZ",
    "ANTEC",
    "APNX",
    "ASUS",
    "AULA",
    "BE QUIET!",
    "BITFENIX",
    "COOLER MASTER",
    "CORSAIR",
    "COUGAR",
    "CUBE GAMING",
    "DEEPCOOL",
    "DIGITAL ALLIANCE",
    "ENERMAX",
    "EMACHINE",
    "ENLIGHT",
    "EK GAMING",
    "EZDIY-FAB",
    "FRACTAL",
    "FSP",
    "GALAX",
    "GAMDIAS",
    "GAMEMAX",
    "GIGABYTE",
    "HAVN",
    "HYTE",
    "INFINITY",
    "INWIN",
    "JONSBO",
    "JONSPLUS",
    "KEBOS",
    "METALLICGEAR",
    "MAGNIUMGEAR",
    "MONTECH",
    "MSI",
    "LIAN LI",
    "NZXT",
    "OCYPUS",
    "PARADOX",
    "PCCOOLER",
    "PHANTEKS",
    "POWERLOGIC",
    "POWER UP",
    "PRIME",
    "RAIDMAX",
    "RAIJINTEK",
    "RAPTOR",
    "SADES",
    "SEGOTEP",
    "SIMBADDA",
    "SILVERSTONE",
    "Tecware",
    "THERMALTAKE",
    "TRYX",
    "VANAEN",
    "VENOMRX",
    "XAGATEK",
    "ZALMAN",
  ],
  "pc-branded": [
    "ACER",
    "ADVAN",
    "APPLE",
    "ASROCK",
    "ASUS",
    "AXIOO",
    "BIOSTAR",
    "COLORFUL",
    "DELL",
    "HP",
    "INTEL NUC",
    "LENOVO",
    "MINIX",
    "MSI",
    "ZOAN",
    "ZOTECH",
    "ZYREX",
  ],
  gadget: [
    "70MAI",
    "ACER",
    "ADVAN",
    "AMAZON",
    "APPLE",
    "ASUS",
    "AVARO",
    "DJI",
    "GARMIN",
    "GOOGLE",
    "GOPRO",
    "HONOR",
    "HUAWEI",
    "INFINIX",
    "INOI",
    "INSTA",
    "IMOO",
    "IQOO",
    "ITEL",
    "LENOVO",
    "MIBRO",
    "MICROSOFT",
    "MOTOROLA",
    "MSI",
    "NINTENDO",
    "OLIKE",
    "OCULUS",
    "OPPO",
    "PICO",
    "PLAUD",
    "PLAYSTATION",
    "PULSE",
    "RAY BAN",
    "REALME",
    "SAMSUNG",
    "STEAM DECK",
    "TECNO",
    "SHARP",
    "VIVO",
    "VILLAON",
    "XIAOMI",
    "BOSE",
    "EDIFIER",
    "JBL",
    "HARMAN KARDON",
    "MARSHALL",
    "MICROSOFT",
    "SONY",
    "ZTE",
  ],
  notebook: [
    "ADVAN",
    "ACER",
    "ASPIRE",
    "APPLE",
    "ASUS",
    "AVITA",
    "AXIOO",
    "DELL",
    "HP",
    "HUAWEI",
    "JUMPER",
    "INFINIX",
    "LENOVO",
    "LEGION",
    "MICROSOFT",
    "MSI",
    "POLYTRON",
    "SAMSUNG",
    "SPC",
    "TECNO",
    "TOSHIBA",
    "XIAOMI",
    "ZYREX",
  ],
  cooler: [
    "1STPLAYER",
    "AEROCOOL",
    "AIGO",
    "ANTEC",
    "ARCTIC",
    "ASUS",
    "AULA",
    "BE QUIET!",
    "COOLER MASTER",
    "CORSAIR",
    "COUGAR",
    "CUBE GAMING",
    "CRYORIG",
    "DEEPCOOL",
    "ENERMAX",
    "FRACTAL",
    "FSP",
    "GAMDIAS",
    "GIGABYTE",
    "HYTE",
    "JONSBO",
    "LIAN LI",
    "MONTECH",
    "MSI",
    "NOCTUA",
    "NZXT",
    "OCYPUS",
    "PARADOX",
    "PCCOOLER",
    "PHANTEKS",
    "POWERLOGIC",
    "PRIME",
    "RAIDMAX",
    "RAIJINTEK",
    "SAPPHIRE",
    "SCYTHE",
    "SEGOTEP",
    "SILVERSTONE",
    "THERMALTAKE",
    "TRYX",
    "VENOMRX",
    "ZALMAN",
  ],
};
